cultivos_iw/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'cultivos_iw'

urlpatterns = [
    path('index/', views.Index.as_view(), name='index'),
    path('', views.Index.as_view(), name='index'),
    path('edit/<int:cultivo_id>/', views.CultivoEditar.as_view(), name='edit'),  
    path('cultivo/delete/<int:cultivo_id>/', views.CultivoEliminar.as_view(), name='delete_cultivo'),
    path('cultivo/details/<int:cultivo_id>/', views.CultivoDetail.as_view(), name='cultivo_details'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prueba_tecnica_iw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cultivos_iw.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

cultivos_iw/models.py
from django.db import models
from django.contrib.auth.hashers import make_password, check_password
from django.core.exceptions import ValidationError



class Cultivo(models.Model):
    TROPICAL = 'Tropical'
    DRY = 'Seco'
    MILD = 'Templado'
    CONTINENTAL = 'Continental'
    COOL = 'Fríos'
    ANYONE = 'Cualquiera'
    
    BEGINNER = 'Principiante'
    MEDIUM = 'Medio'
    HARD = 'Difícil'
    
    SPRING = 'Primavera'
    SUMMER = 'Verano'
    AUTUMN = 'Otoño'
    WINTER = 'Invierno'
    

    SUN ='Sol'
    HALF_SHADOW = 'Media Sombra'
    SHADOW = 'Sombra'

    VEGETABLES = 'Hortalizas'
    FLOWERS = 'Flores'    
    AROMATICS = 'Aromáticas'

    WEATHER_CHOICES = [
        (TROPICAL, 'Tropical'),
        (DRY, 'Seco'),
        (MILD, 'Templado'),
        (CONTINENTAL, 'Continental'),
        (COOL, 'Fríos'),
        (ANYONE, 'Cualquiera'),
    ]
    
    DIFFICULTY_CHOICES = [
        (BEGINNER, 'Principiante'),
        (MEDIUM, 'Medio'),
        (HARD, 'Difícil'),
    ]
    
    SEASON_CHOICES = [
        (SPRING, 'Primavera'),
        (SUMMER, 'Verano'),
        (AUTUMN, 'Otoño'),
        (WINTER, 'Invierno'),
        (ANYONE, 'Cualquiera'),
    ]
    
    ILLUMINATION_CHOICES = [
        (SUN, 'Sol'), 
        (HALF_SHADOW, 'Media Sombra'),
        (SHADOW, 'Sombra')   
    ]
    
    TYPE_CHOICES = [
    (VEGETABLES, 'Hortalizas'),
    (FLOWERS, 'Flores'),
    (AROMATICS, 'Aromáticas')    
    ]
    
    
    title = models.CharField(max_length=100)
    description = models.TextField()
    weather = models.CharField(max_length=12, choices=WEATHER_CHOICES, default=ANYONE)
    image = models.ImageField(upload_to='cultivos/')
    quantity = models.PositiveIntegerField()
    difficulty = models.CharField(max_length=12, choices=DIFFICULTY_CHOICES, default=BEGINNER)
    season = models.CharField(max_length=10, choices=SEASON_CHOICES, default=SPRING)
    illumination = models.CharField(max_length=12, choices=ILLUMINATION_CHOICES, default=SUN)
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, default=VEGETABLES)
    
    def __str__(self):
        return self.title

cultivos_iw/forms.py
from django import forms
from .models import Cultivo

class CultivoForm(forms.ModelForm):
    class Meta:
        model = Cultivo
        fields = ['title', 'description', 'weather', 'image', 'quantity', 'difficulty', 'season', 'illumination', 'type']
        labels = {
            'title': 'Título',
            'description': 'Descripción',
            'weather': 'Clima',
            'quantity': 'Cantidad',
            'difficulty': 'Dificultad',
            'season': 'Estación',
            'illumination': 'Iluminación',
            'type': 'Tipo',
            'image': 'Imagen'
        }
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Título del cultivo'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Detalles y características sobre el cultivo'
            }),
            'weather': forms.Select(attrs={
                'class': 'form-select'
            }),
            'quantity': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Cantidad'
            }),
            'difficulty': forms.Select(attrs={
                'class': 'form-select'
            }),
            'season': forms.Select(attrs={
                'class': 'form-select'
            }),
            'illumination': forms.Select(attrs={
                'class': 'form-select'
            }),
            'type': forms.Select(attrs={
                'class': 'form-select'
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            })
        }

cultivos_iw/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import TemplateView, CreateView, View
from django.http import HttpResponse
from .models import *
from .forms import *
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth import authenticate, login



@method_decorator(login_required, name='dispatch')
class Index(View):
    model = Cultivo
    form_class = CultivoForm
    template_name = 'cultivos_iw/index.html'
    success_url = reverse_lazy('cultivos_iw:index')

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        cultivos = Cultivo.objects.all()
        return render(request, self.template_name, {'form': form, 'cultivos': cultivos})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        return render(request, self.template_name, {'form': form})

    def delete(self, request, cultivo_id):
        cultivo = get_object_or_404(Cultivo, pk=cultivo_id)
        cultivo.delete()
        return redirect(self.success_url)
    
@method_decorator(login_required, name='dispatch')
class CultivoDetail(View):
   model = Cultivo
   template_name = 'cultivos_iw/details.html'
   
   def get(self, request, cultivo_id, *args, **kwargs):
        cultivo = get_object_or_404(Cultivo, id=cultivo_id)
        return render(request, self.template_name, {'cultivo': cultivo})

@method_decorator(login_required, name='dispatch')
class CultivoEditar(View):
    template_name = 'cultivos_iw/edit.html'
    form_class = CultivoForm
    success_url = reverse_lazy('cultivos_iw:index')
    def get(self, request, cultivo_id, *args, **kwargs):
        cultivo = get_object_or_404(Cultivo, id=cultivo_id)
        form = self.form_class(instance=cultivo)
        return render(request, self.template_name, {'form': form, 'cultivo': cultivo})

    def post(self, request, cultivo_id, *args, **kwargs):
        cultivo = get_object_or_404(Cultivo, id=cultivo_id)
        form = self.form_class(request.POST, request.FILES, instance=cultivo)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        return render(request, self.template_name, {'form': form, 'cultivo': cultivo})
    
@method_decorator(login_required, name='dispatch')
class CultivoEliminar(View):
    template_name = 'cultivos_iw/index.html'

    def get(self, request, cultivo_id, *args, **kwargs):
        cultivo = get_object_or_404(Cultivo, id=cultivo_id)
        return render(request, self.template_name, {'cultivo': cultivo})

    def post(self, request, cultivo_id, *args, **kwargs):
        cultivo = get_object_or_404(Cultivo, id=cultivo_id)
        cultivo.delete()
        return JsonResponse({'message': 'Cultivo eliminado correctamente'}) 

cultivos_iw/templates/cultivos_iw/index.html
{% extends 'layout.html' %}

{% block content %}

<div class="container-fluid d-flex p-0" style="height: 100vh;">

  <!-- Sidebar -->
  <div class="col-2">
    <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="height: 100vh;">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="72" height="57" fill="white"
          class="bi bi-flower3 align-self-center" viewBox="0 0 16 16">
          <path
            d="M11.424 8c.437-.052.811-.136 1.04-.268a2 2 0 0 0-2-3.464c-.229.132-.489.414-.752.767C9.886 4.63 10 4.264 10 4a2 2 0 1 0-4 0c0 .264.114.63.288 1.035-.263-.353-.523-.635-.752-.767a2 2 0 0 0-2 3.464c.229.132.603.216 1.04.268-.437.052-.811.136-1.04.268a2 2 0 1 0 2 3.464c.229-.132.489-.414.752-.767C6.114 11.37 6 11.736 6 12a2 2 0 1 0 4 0c0-.264-.114-.63-.288-1.035.263.353.523.635.752.767a2 2 0 1 0 2-3.464c-.229-.132-.603-.216-1.04-.268M9 4a2 2 0 0 1-.045.205q-.059.2-.183.484a13 13 0 0 1-.637 1.223L8 6.142l-.135-.23a13 13 0 0 1-.637-1.223 4 4 0 0 1-.183-.484A2 2 0 0 1 7 4a1 1 0 1 1 2 0M3.67 5.5a1 1 0 0 1 1.366-.366 2 2 0 0 1 .156.142q.142.15.326.4c.245.333.502.747.742 1.163l.13.232-.265.002a13 13 0 0 1-1.379-.06 4 4 0 0 1-.51-.083 2 2 0 0 1-.2-.064A1 1 0 0 1 3.67 5.5m1.366 5.366a1 1 0 0 1-1-1.732l.047-.02q.055-.02.153-.044.202-.048.51-.083a13 13 0 0 1 1.379-.06q.135 0 .266.002l-.131.232c-.24.416-.497.83-.742 1.163a4 4 0 0 1-.327.4 2 2 0 0 1-.155.142M9 12a1 1 0 0 1-2 0 2 2 0 0 1 .045-.206q.058-.198.183-.483c.166-.378.396-.808.637-1.223L8 9.858l.135.23c.241.415.47.845.637 1.223q.124.285.183.484A1.3 1.3 0 0 1 9 12m3.33-6.5a1 1 0 0 1-.366 1.366 2 2 0 0 1-.2.064q-.202.048-.51.083c-.412.045-.898.061-1.379.06q-.135 0-.266-.002l.131-.232c.24-.416.497-.83.742-1.163a4 4 0 0 1 .327-.4q.07-.074.114-.11l.041-.032a1 1 0 0 1 1.366.366m-1.366 5.366a2 2 0 0 1-.155-.141 4 4 0 0 1-.327-.4A13 13 0 0 1 9.74 9.16l-.13-.232.265-.002c.48-.001.967.015 1.379.06q.308.035.51.083.098.024.153.044l.048.02a1 1 0 1 1-1 1.732zM8 9a1 1 0 1 1 0-2 1 1 0 0 1 0 2" />
        </svg>
        <span class="fs-4">Grow Life</span>
      </a>
      <hr>
      <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
          <a href="{% url 'cultivos_iw:index' %}" class="nav-link nav-hover-effect" aria-current="page" style="color:white">
            <svg class="bi pe-none me-2" width="16" height="16">
              <use xlink:href="#home"></use>
            </svg>
            Cultivos
          </a>
        </li>
      </ul>
      <hr>
    </div>
  </div>

  <!-- Main content area -->
  <div class="col-10 p-0">
    <!-- Header -->
    <header class="py-3 border-bottom bg-light">
      <div class="d-flex justify-content-end align-items-center me-3">
        <div class="dropdown">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
            aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
            <span class="ms-2">{{user.username}}</span>
          </a>
          <ul class="dropdown-menu dropdown-menu-end text-small shadow">
            <form method="post" action="{% url 'logout' %}" id="logout-form">
                    {% csrf_token %}
                    <button type="submit" class="dropdown-item">Cerrar sesión</button>
            </form>
          </ul>
        </div>
      </div>
    </header>

    <!-- Content area -->
    <div class="container-fluid d-flex flex-column p-4">
      <div class="col-12 d-flex justify-content-end">
          <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#cultivoModal">Agregar cultivo</button>
      </div>
      <div class="col-12 d-flex">
          <div class="container">
            <div class="row">
              {% for cultivo in cultivos %}
              <div class="col-12 col-md-6 col-lg-3 d-flex">
                <div class="card m-3" style="width: 18rem;">
                  <img src="{{ cultivo.image.url }}" class="card-img-top" alt="{{ cultivo.title }}" style="width: 100%; height: 180px; object-fit: cover;">
                  <div class="card-body d-flex flex-column justify-content-center">
                    <h5 class="card-title d-flex justify-content-center">{{ cultivo.title }}</h5>
                    <p class="card-text d-flex justify-content-center">{{ cultivo.difficulty }}</p>
                    <div class="d-flex justify-content-center">
                      <a type="button" class="btn btn-outline-success m-1 btn-details"
                        href="{% url 'cultivos_iw:cultivo_details' cultivo.id %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye"
                          viewBox="0 0 16 16">
                          <path
                            d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z">
                          </path>
                          <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"></path>
                        </svg>
                      </a>
                      <a type="button" class="btn btn-outline-primary m-1 btn-edit"
                        href="{% url 'cultivos_iw:edit' cultivo.id %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil"
                          viewBox="0 0 16 16">
                          <path
                            d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325">
                          </path>
                        </svg>
                      </a>
                      <button id="eliminarCultivoBtn-{{ cultivo.id }}" type="button" class="btn btn-outline-danger m-1 btn-delete"
                        data-id="{{ cultivo.id }}" data-bs-toggle="modal" data-bs-target="#eliminarCultivoModal">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3"
                          viewBox="0 0 16 16">
                          <path
                            d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5">
                          </path>
                        </svg>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>

      </div>
      
    </div>
  </div>

</div>

<!-- Modal crear cultivo-->
<div class="modal fade" id="cultivoModal" tabindex="-1" aria-labelledby="cultivoModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="cultivoModalLabel">Agregar Cultivo</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="mb-3">
            {{ form.title.label_tag }}
            {{ form.title }}
          </div>
          <div class="mb-3">
            {{ form.description.label_tag }}
            {{ form.description }}
          </div>
          <div class="row">
            <div class="col-md-6 mb-3">
              {{ form.weather.label_tag }}
              {{ form.weather }}
            </div>
            <div class="col-md-6 mb-3">
              {{ form.season.label_tag }}
              {{ form.season }}
            </div>
          </div>
          <div class="row">
              <div class="col-md-6 mb-3">
                {{ form.quantity.label_tag }}
                {{ form.quantity }}
              </div>
              <div class="col-md-6 mb-3">
                {{ form.difficulty.label_tag }}
                {{ form.difficulty }}
              </div>
          </div>
          <div class="row">
              <div class="col-md-6 mb-3">
                {{ form.illumination.label_tag }}
                {{ form.illumination }}
              </div>
              <div class="col-md-6 mb-3">
                {{ form.type.label_tag }}
                {{ form.type }}
              </div>
          </div>
          <div class="mb-3">
            {{ form.image.label_tag }}
            {{ form.image }}
          </div>
          <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
      </div>
    </div>
  </div>
</div>


<!-- Modal de confirmación de eliminación -->
<div class="modal fade" id="eliminarCultivoModal" tabindex="-1" aria-labelledby="eliminarCultivoModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="eliminarCultivoModalLabel">Confirmar eliminación</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ¿Estás seguro de que deseas eliminar este cultivo?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-danger" id="confirmarEliminar">Eliminar</button>
      </div>
    </div>
  </div>
</div>



<!-- Script para manejar la eliminación del cultivo -->
<script>
  document.addEventListener('DOMContentLoaded', function() {
  var confirmarEliminarBtn = document.getElementById('confirmarEliminar');
  var eliminarBtns = document.querySelectorAll('.btn-delete');

  eliminarBtns.forEach(function(btn) {
    btn.addEventListener('click', function() {
      var cultivoId = this.getAttribute('data-id');
      confirmarEliminarBtn.setAttribute('data-id', cultivoId);
    });
  });

  if (confirmarEliminarBtn) {
    confirmarEliminarBtn.addEventListener('click', function() {
      var cultivoId = this.getAttribute('data-id');
      console.log(cultivoId);
      fetch('/cultivo/delete/' + cultivoId + '/', {
        method: 'POST',
        headers: {
          'X-CSRFToken': '{{ csrf_token }}'
        }
      })
      .then(response => response.json())
      .then(data => {
        console.log(data.message);
        window.location.reload(); // Recargar la página después de eliminar el cultivo
      })
      .catch(error => console.error('Error:', error));
    });
  }
});


</script>

{% endblock %}

{% block js %}

{% endblock js %}

templates/layout.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <title>Cultivos IW</title>
        <meta name="description" content="">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">
    </head>
    <body class="{% if request.path == '/accounts/login/' and request.GET.next == '/' %}bodyMain justify-content-center align-items-center{% elif request.path == '/index' or request.path == '/index/' %}bodyIndex {% else %}bodySecondary justify-content-center align-items-center{% endif %} container-fluid d-flex p-0 " style="height: 100vh; width: 100vw; margin: 0;">
        
            {% block content %}
            <!-- Aqui se muestra el contenido de los templates de cultivos iw -->
            {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
       
        
    </body>
</html>